[project]
name = "sentiment-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "langgraph>=0.5.2",
    "torch>=2.7.1",
    "Flask>=2.0.0"
]
